/**
 * @yantrakit/vedic-icons
 *
 * Pure CSS icon library. Import the CSS file to use:
 *
 * @example
 * ```js
 * import '@yantrakit/vedic-icons/css';
 * ```
 *
 * Icons carry their HINDI name: the anklet is `vi-payal`, the tiger is `vi-baagh`.
 * The English name is kept as an alias and renders the same glyph, so `vi-anklet`
 * and `vi-tiger` still work.
 *
 * Devanagari letters are always prefixed — `vi-devanagari-ka`, never a bare `vi-ka`.
 * A one or two character class name in a shared namespace collides too easily.
 *
 * @example
 * ```html
 * <i class="vi vi-solid vi-payal"></i>
 * <i class="vi vi-solid vi-devanagari-ka"></i>
 * ```
 */

/** List of all available icon names. */
export const icons = ['aam','aam-fal','aam-ka-ped','aarti','aarti-02','aditi','adrak','agarbatti','agni','agni-baan','agra-ka-kila','ahimsa','akash-kandil','alamelu','anahat','ananta-granthi','ardhanareeswara','ardhanarishvara-02','ashirvad','ashoka','ashoka-chakra','auto','auto-02','ayurved','ayurved-katori','ayyappa','baagh','baagh-02','baati','bail','bail-02','baja','balaji','balarama','bali-mandir','bandanwar','bandanwar-mala','bandar','bandar-02','bandar-03','bangles','barfi','bargad','been','bhagwa-dhwaj','bhang','bhangra','bharat-naksha','bharatiya-nari','bhojan','bindi-wali','biryani','bodhi','bodhu-boron','brahma','brahmin','brihaspati','buddha','calendar-holi','calendar-kite','calendar-om','calendar-pongol','calendar-swastika','chai','chakli','chakra','chakra-02','chand','chandan-lep','chandi','chandra','char-minar','charan','chawal-bora','chawal-sabzi','chhatra','chhikka','chikki','chutney','conch','cricket-ball','cricket-bat','cricket-cap','cricket-gloves','cricket-helmet','cricket-kit','cricket-stadium','cricket-umpire','cricketer','dalchini','damru','deepak','deepak-02','deepak-03','deepak-04','devanagari-a','devanagari-aa','devanagari-ae','devanagari-ai','devanagari-au','devanagari-aw','devanagari-ba','devanagari-bha','devanagari-cha','devanagari-chha','devanagari-da','devanagari-dda','devanagari-dda-nukta','devanagari-ddha','devanagari-ddha-nukta','devanagari-dha','devanagari-e','devanagari-fa','devanagari-ga','devanagari-gha','devanagari-ghha','devanagari-ha','devanagari-i','devanagari-ii','devanagari-ja','devanagari-jha','devanagari-ka','devanagari-kha','devanagari-khha','devanagari-la','devanagari-li','devanagari-lla','devanagari-llha','devanagari-lri','devanagari-ma','devanagari-na','devanagari-nga','devanagari-nna','devanagari-nya','devanagari-o','devanagari-pa','devanagari-pha','devanagari-qa','devanagari-ra','devanagari-ri','devanagari-rra','devanagari-rri','devanagari-sa','devanagari-sha','devanagari-ssa','devanagari-ta','devanagari-tha','devanagari-tta','devanagari-ttha','devanagari-u','devanagari-uu','devanagari-va','devanagari-ya','devanagari-yya','devanagari-za','devi','devi-netra','dhanteras','dhanush','dhanush-baan','dhol','dhol-02','dholak','dhoop-daani','dhyaan','dhyaan-02','diwali-deepak','diwali-diye','dum-aloo','durga','ektara','evil-eye','falooda','gaay','gaay-02','gaay-03','gadaa','ganatantra-divas','ganesha','ganga','ganga-devi','garuda','gateway','gau-mata','gayatri','gehun','genda','ghada','ghee','giddha','granth-om','granth-swastika','gujiya','gulab-jamun','gurudwara','guruji','haar','haath-mein-rupaya','haath-pankha','haath-rupaya','haathi','haathi-02','hamsa','handi','hans','hanumaan','hanumaan-02','hanuman-02','harihara','harmandir-sahib','havan','havan-agni','hawa-mahal-jaipur','hindi-akshar','hiran','hiran-02','holi','hukka','humayun-ka-maqbara','imam-dasta','imli','india-gate-02','india-gate-dilli','indra','jadi-booti','jagannatha','jaisalmer','jalebi','jama-masjid','jantar-mantar','jap-mala','jhandi','jhumka','jhumka-02','kalash','kalash-swastika','kalgi','kali','kalki','kamadeva','kamal','kamal-mandir','kamal-phool','kamdhenu-gau','kanji-vada','kapas','karm','karni-mata','kartavya-path','kartikeya','kathakali-nritya','kheer','khuder-bhat','konark','krishna','krishna-02','kuber','kubera','kubera-02','kulfi','kumkum','kurma','laalten','laalten-02','laddoo','laddu','ladoo-katori','lakshmi','lal-mirch','lassi','laung','maala','mahabali','malai-kofta','malai-kulfi','mandal','mandal-02','mandap','mandir','mangal-snan','mangal-sutra','mani-chakra','masala','masala-dosa','mathri','matsya-avatar','medu-vada','meenakshi','mehndi','mehndi-haath','mitra','mohini','momo','mor','mridang','mughlai','naag','naag-02','naan-roti','nalla-pusalu','namaskar','narasimha','nariyal-doodh','nariyal-ka-ped','nariyal-ke-ped','nariyal-pani','nariyal-tel','nataraja','nimantran-patra','note','okhli','omkar','paan','pads','pagdi-02','palki','pandit','paneer-makhani','pangong-jheel','parashurama','parashurama-02','parivar','parliament','parvati','pataka','pataka-02','pataka-03','patang','patra','pav-bhaji','payal','payal-02','peda','phuljhadi','pichkaari','pichola-jheel','pind-swed','pongal-02-parv','pongal-parv','pooja','prambanan','pranam','pujari','qutub','radha','rakhi','rakhi-02','rama','rang-balti','rangoli-kolam','rashtrapati-bhawan','ravana','red-fort','rocket-pataka','rudraaksh','rupaya','saag-paneer','saanp','saap','saat-phere','sabzi-katori','sadhu','sadhya','samosa','samosa-chai','samose','sandesh','sanskrit','santur','sapta-matrika','saraswati','sardar','sardar-02','sardar-chehra','saree','sarod','scroll-02','scroll-03','scroll-quill','scroll-rolled','scroll-rolled02','sesha','shaadi-mandap','shahnai','shahnai-02','shakha-pola','shakti','shani','sher','sher-02','shirodhaara','shiva','shivling','shola-ghar','shri','sikka','sindur','sita','sitar','sitar-02','speakers','stoop','stri','stumps','surya','surya-devta','swadhisthan','swarmandal','swastik','swastik-02','swastik-granth','swastik-kamal','tabla','tabla-02','tabla-03','tadpatra','taj','tanpura','teeka','teesri-aankh','thaali','thandai','thunderbolt','tikka-masala','tiranga','tiranga-02','tiranga-halwa','toran','toran-02','trident-02','tridevi','trishool','trophy','tulsi-patta','turmeric','vada-pav','vamana','varaha','varaha-02','varuna','vasudeva','ved','veerta-puraskar','vishnu','vishnu-02','vishwakarma','yagya','yagya-02','yama','yantr','yudh-smarak'] as const;

/** Type representing a valid icon name. */
export type iIconName = (typeof icons)[number];

/** Alias -> canonical icon name. Mostly the English name for a Hindi-named icon. */
export const aliases: Record<string, iIconName> = {
  'adrak-ginger': 'adrak',
  'agni-dev': 'agni',
  'agra-fort': 'agra-ka-kila',
  'ahimsa-hand': 'ahimsa',
  'ampayar': 'cricket-umpire',
  'anahata-chakra': 'anahat',
  'anklet': 'payal',
  'anklet-02': 'payal-02',
  'arrow-fire': 'agni-baan',
  'ashirwad-blessing': 'ashirvad',
  'auto-rickshaw': 'auto',
  'auto-rickshaw-02': 'auto-02',
  'ayurveda': 'ayurved',
  'ayurvedic-bowl': 'ayurved-katori',
  'ayurvedic-mortar': 'okhli',
  'balinese-pura': 'bali-mandir',
  'balla': 'cricket-bat',
  'bansuri': 'shahnai-02',
  'banyan-tree': 'bargad',
  'bhang-leaf': 'bhang',
  'bhangra-dancer': 'bhangra',
  'bhikkhu-monk': 'sadhu',
  'bhikshu': 'sadhu',
  'bhonpu': 'speakers',
  'bindi-woman': 'bindi-wali',
  'blessing': 'ashirvad',
  'bodhi-leaf': 'bodhi',
  'bow-arrow': 'dhanush-baan',
  'brahman-elder': 'brahmin',
  'bull': 'bail',
  'bull-02': 'bail-02',
  'bunting-garland': 'bandanwar-mala',
  'calendar-republic-day': 'ganatantra-divas',
  'chakras': 'chakra',
  'chandan': 'chandan-lep',
  'chandra-02': 'chand',
  'chandra-devta': 'chandra',
  'charminar': 'char-minar',
  'chhatra-parasol': 'chhatra',
  'chhatri': 'chhatra',
  'chiki': 'chikki',
  'chilli-pepper': 'lal-mirch',
  'chutney-jar': 'chutney',
  'cobra': 'saap',
  'coconut-milk': 'nariyal-doodh',
  'coconut-oil': 'nariyal-tel',
  'coconut-palm': 'nariyal-ka-ped',
  'coconut-palms': 'nariyal-ke-ped',
  'coin': 'sikka',
  'colour-bucket': 'rang-balti',
  'cow': 'gaay',
  'cow-02': 'gaay-02',
  'cow-03': 'gaay-03',
  'cricket-pads': 'pads',
  'cricket-stumps': 'stumps',
  'cricket-topi': 'cricket-cap',
  'cricket-trophy': 'trophy',
  'curry-bowl': 'sabzi-katori',
  'curry-rice': 'chawal-sabzi',
  'dalchini-cinnamon': 'dalchini',
  'damaru': 'damru',
  'dangle-earrings': 'jhumka',
  'dangle-earrings-02': 'jhumka-02',
  'dastane': 'cricket-gloves',
  'deer': 'hiran',
  'deer-02': 'hiran-02',
  'devi-eyes': 'devi-netra',
  'dhanteras-kalash': 'dhanteras',
  'dhol-drum': 'dhol-02',
  'diwali-candles': 'diwali-diye',
  'diwali-lamps': 'diwali-deepak',
  'diwali-sparkles': 'phuljhadi',
  'diya': 'deepak',
  'diya-02': 'deepak-02',
  'diya-03': 'deepak-03',
  'diya-04': 'deepak-04',
  'doli': 'palki',
  'elephant': 'haathi',
  'elephant-02': 'haathi-02',
  'endless-knot': 'ananta-granthi',
  'face-male-sikh': 'sardar-chehra',
  'family-gathering': 'parivar',
  'female': 'stri',
  'festive-flags': 'jhandi',
  'firecracker': 'pataka',
  'firecracker-02': 'pataka-02',
  'firecraker': 'pataka-03',
  'footprint': 'charan',
  'gada': 'gadaa',
  'ganga-nadi': 'ganga',
  'ganges-river': 'ganga',
  'gateway-of-india': 'gateway',
  'gend': 'cricket-ball',
  'genda-phool': 'genda',
  'ghee-jar': 'ghee',
  'giddha-dancer': 'giddha',
  'golden-temple': 'harmandir-sahib',
  'gujia': 'gujiya',
  'gurdwara': 'gurudwara',
  'guru': 'guruji',
  'haar-necklace': 'haar',
  'haldi': 'turmeric',
  'hamsa-eye': 'evil-eye',
  'hamsa-hand': 'hamsa',
  'hand-holding-rupee': 'haath-mein-rupaya',
  'hand-rupee-02': 'haath-rupaya',
  'handi-pot': 'handi',
  'harmonium': 'baja',
  'havan-fire': 'havan-agni',
  'hawa-mahal': 'hawa-mahal-jaipur',
  'henna-hand': 'mehndi',
  'herbal-leaf': 'jadi-booti',
  'hinduist-flag': 'bhagwa-dhwaj',
  'homa-havan': 'havan',
  'hookah': 'hukka',
  'humayuns-tomb': 'humayun-ka-maqbara',
  'imli-tamarind': 'imli',
  'incense': 'agarbatti',
  'incense-burner': 'dhoop-daani',
  'india-gate': 'india-gate-dilli',
  'india-map': 'bharat-naksha',
  'indian-flag': 'tiranga',
  'indian-flag-02': 'tiranga-02',
  'indian-food': 'bhojan',
  'indian-woman': 'bharatiya-nari',
  'jaisalmer-fort': 'jaisalmer',
  'japa-mala': 'jap-mala',
  'kamdhenu': 'kamdhenu-gau',
  'kandeel': 'akash-kandil',
  'kandil': 'akash-kandil',
  'kapas-cotton': 'kapas',
  'karma': 'karm',
  'kathakali': 'kathakali-nritya',
  'khiladi': 'cricketer',
  'kite': 'patang',
  'konark-sun-temple': 'konark',
  'kumbh-kalash': 'kalash',
  'kumkuma': 'kumkum',
  'ladoo': 'laddoo',
  'ladoo-bowl': 'ladoo-katori',
  'lake-pichola': 'pichola-jheel',
  'lal-kila-agra': 'agra-ka-kila',
  'lal-qila': 'red-fort',
  'lantern': 'laalten',
  'lantern-02': 'laalten-02',
  'laung-clove': 'laung',
  'lingam': 'shivling',
  'lion': 'sher',
  'lion-02': 'sher-02',
  'lotus': 'kamal-phool',
  'lotus-flower': 'kamal',
  'lotus-temple': 'kamal-mandir',
  'loudspeakers': 'speakers',
  'maidan': 'cricket-stadium',
  'mala': 'maala',
  'male-sikh': 'sardar',
  'male-sikh02': 'sardar-02',
  'mandala': 'mandal',
  'mandala-02': 'mandal-02',
  'mangala-snanam': 'mangal-snan',
  'mangalsutra': 'mangal-sutra',
  'mango': 'aam',
  'mango-tree': 'aam-ka-ped',
  'mangoes': 'aam-fal',
  'marigold': 'genda',
  'matka': 'ghada',
  'matka-water-jar': 'ghada',
  'matsya': 'matsya-avatar',
  'meditation': 'dhyaan',
  'meditation-02': 'dhyaan-02',
  'meenakshi-temple': 'meenakshi',
  'mehndi-hand': 'mehndi-haath',
  'mirchi': 'lal-mirch',
  'monkey': 'bandar',
  'monkey-02': 'bandar-02',
  'monkey-03': 'bandar-03',
  'mortar-pestle': 'imam-dasta',
  'mridangam': 'mridang',
  'mughlai-curry': 'mughlai',
  'murukku': 'chakli',
  'naans': 'naan-roti',
  'naga': 'naag',
  'naga-02': 'naag-02',
  'nallapusalu': 'nalla-pusalu',
  'namaste': 'pranam',
  'namaste-hands': 'namaskar',
  'nandi': 'bail',
  'national-bravery': 'veerta-puraskar',
  'nazar': 'evil-eye',
  'nimantran': 'nimantran-patra',
  'okhli-musal': 'imam-dasta',
  'om': 'omkar',
  'paduka': 'charan',
  'palm-leaf-manuscript': 'tadpatra',
  'pandit-ji': 'brahmin',
  'pangong-tso': 'pangong-jheel',
  'pankha': 'haath-pankha',
  'pankha-hand-fan': 'haath-pankha',
  'peacock': 'mor',
  'peepal-patta': 'bodhi',
  'peti': 'baja',
  'pichkari': 'pichkaari',
  'pinda-sweda': 'pind-swed',
  'pongal': 'pongal-parv',
  'pongal-02': 'pongal-02-parv',
  'prayer-wheel': 'mani-chakra',
  'priest': 'pujari',
  'puja': 'pooja',
  'pundit': 'pandit',
  'pura': 'bali-mandir',
  'purna-kumbha': 'kalash',
  'qutub-minar': 'qutub',
  'rajpath': 'kartavya-path',
  'raksha-bandhan': 'rakhi',
  'raksha-bandhan-02': 'rakhi-02',
  'rangoli': 'rangoli-kolam',
  'rashtrapati-bhavan': 'rashtrapati-bhawan',
  'rice-sack': 'chawal-bora',
  'rickshaw': 'auto',
  'rocket-firecracker': 'rocket-pataka',
  'rudraksha': 'rudraaksh',
  'rui': 'kapas',
  'rupaya-note': 'note',
  'rupee-coin': 'rupaya',
  'rupee-note': 'note',
  'sacred-cow': 'gau-mata',
  'samosas': 'samose',
  'sansad-bhavan': 'parliament',
  'sansad-bhawan': 'parliament',
  'santoor': 'santur',
  'saptapadi': 'saat-phere',
  'sari': 'saree',
  'scroll': 'patra',
  'shaadi-card': 'nimantran-patra',
  'shankh': 'conch',
  'shehnai': 'shahnai',
  'shirodhara': 'shirodhaara',
  'shree': 'shri',
  'sindoor': 'sindur',
  'sindoor-daani': 'kumkum',
  'snake': 'saanp',
  'sonar-kila': 'jaisalmer',
  'speaker': 'speakers',
  'stupa': 'stoop',
  'surya-dev': 'surya-devta',
  'svadhishthana': 'swadhisthan',
  'swan': 'hans',
  'swarn-mandir': 'harmandir-sahib',
  'swastika': 'swastik',
  'swastika-02': 'swastik-02',
  'swastika-book': 'swastik-granth',
  'swastika-lotus': 'swastik-kamal',
  'taj-mahal': 'taj',
  'temple': 'mandir',
  'thali': 'thaali',
  'third-eye': 'teesri-aankh',
  'tiger': 'baagh',
  'tiger-02': 'baagh-02',
  'tilak': 'teeka',
  'toran-lights': 'bandanwar',
  'trishool-02': 'trident-02',
  'trishul': 'trishool',
  'trishul-02': 'trident-02',
  'tulsi': 'tulsi-patta',
  'turban-02': 'pagdi-02',
  'turla-turban-crest': 'kalgi',
  'turra': 'kalgi',
  'vajr': 'thunderbolt',
  'vajra': 'thunderbolt',
  'vedas': 'ved',
  'veena': 'been',
  'viket': 'stumps',
  'vivah-mandap': 'shaadi-mandap',
  'war-memorial': 'yudh-smarak',
  'wedding-invitation': 'nimantran-patra',
  'wedding-mandap': 'shaadi-mandap',
  'wheat': 'gehun',
  'yagna': 'yagya',
  'yagna-02': 'yagya-02',
  'yantra': 'yantr'
};

/** Every alias name. */
export const aliasNames = Object.keys(aliases) as readonly string[];

/** Canonical icon name for any name or alias. */
export function canonicalIcon(name: string): iIconName | undefined {
  if ((icons as readonly string[]).includes(name)) return name as iIconName;
  return aliases[name];
}

/** Resolve any name or alias to the icon's own (Hindi) name. */
export function resolveIcon(name: string): iIconName | undefined {
  return canonicalIcon(name);
}
