/**
 * @yantrakit/vedic-icons
 *
 * Pure CSS icon library. Import the CSS file to use:
 *
 * @example
 * ```js
 * import '@yantrakit/vedic-icons/css';
 * ```
 *
 * @example
 * ```html
 * <i class="vi vi-diya"></i>
 * ```
 *
 * Most icons also answer to a Hindi alias, so `vi-baagh` and `vi-tiger` render the same
 * glyph. Aliases are ADDITIVE — no published class name changed. An alias exists only where
 * the Hindi name genuinely differs, and never where it would shadow a real icon: `ladoo`,
 * `thali`, `dhanush` and `toran` are icons in their own right, not aliases.
 *
 * @example
 * ```html
 * <i class="vi vi-baagh"></i>
 * ```
 */

/** List of all available icon names. */
export const icons = ['aarti','aarti-02','aditi','adrak-ginger','agni-dev','agra-fort','ahimsa-hand','alamelu','anahata-chakra','anklet','anklet-02','ardhanareeswara','ardhanarishvara-02','arrow-fire','ashirwad-blessing','ashoka','ashoka-chakra','auto-rickshaw','auto-rickshaw-02','ayurveda','ayurvedic-bowl','ayurvedic-mortar','ayyappa','baati','balaji','balarama','balinese-pura','bangles','banyan-tree','barfi','bhang-leaf','bhangra-dancer','bhikkhu-monk','bindi-woman','biryani','bodhi-leaf','bodhu-boron','brahma','brahman-elder','brihaspati','buddha','bull','bull-02','bunting-garland','calendar-holi','calendar-kite','calendar-om','calendar-pongol','calendar-republic-day','calendar-swastika','chai','chakra-02','chakras','chandan','chandi','chandra','chandra-02','charminar','chhatra-parasol','chhikka','chiki','chilli-pepper','chutney-jar','cobra','coconut-milk','coconut-oil','coconut-palm','coconut-palms','coin','colour-bucket','cow','cow-02','cow-03','cricket-ball','cricket-bat','cricket-cap','cricket-gloves','cricket-helmet','cricket-kit','cricket-pads','cricket-stadium','cricket-stumps','cricket-trophy','cricket-umpire','cricketer','curry-bowl','curry-rice','dalchini-cinnamon','damaru','dangle-earrings','dangle-earrings-02','deer','deer-02','devanagari-a','devanagari-aa','devanagari-ae','devanagari-ai','devanagari-au','devanagari-aw','devanagari-ba','devanagari-bha','devanagari-cha','devanagari-chha','devanagari-da','devanagari-dda','devanagari-dda-nukta','devanagari-ddha','devanagari-ddha-nukta','devanagari-dha','devanagari-e','devanagari-fa','devanagari-ga','devanagari-gha','devanagari-ghha','devanagari-ha','devanagari-i','devanagari-ii','devanagari-ja','devanagari-jha','devanagari-ka','devanagari-kha','devanagari-khha','devanagari-la','devanagari-li','devanagari-lla','devanagari-llha','devanagari-lri','devanagari-ma','devanagari-na','devanagari-nga','devanagari-nna','devanagari-nya','devanagari-o','devanagari-pa','devanagari-pha','devanagari-qa','devanagari-ra','devanagari-ri','devanagari-rra','devanagari-rri','devanagari-sa','devanagari-sha','devanagari-ssa','devanagari-ta','devanagari-tha','devanagari-tta','devanagari-ttha','devanagari-u','devanagari-uu','devanagari-va','devanagari-ya','devanagari-yya','devanagari-za','devi','devi-eyes','dhanteras-kalash','dhanush','dhanush-baan','dhol','dhol-drum','dholak','diwali-candles','diwali-lamps','diwali-sparkles','diya','diya-02','diya-03','diya-04','doli','dum-aloo','durga','ektara','elephant','elephant-02','endless-knot','face-male-sikh','falooda','family-gathering','female','festive-flags','firecracker','firecracker-02','firecraker','flute','footprint','gada','ganesha','ganga-devi','ganges-river','garuda','gateway-of-india','gayatri','ghee-jar','giddha-dancer','golden-temple','granth-om','granth-swastika','gujia','gulab-jamun','gurdwara','guru','haar-necklace','haldi','hamsa-eye','hamsa-hand','hand-holding-rupee','hand-rupee-02','handi-pot','hanumaan','hanumaan-02','hanuman-02','harihara','harmonium','havan-fire','hawa-mahal','henna-hand','herbal-leaf','hindi-akshar','hinduist-flag','holi','homa-havan','hookah','humayuns-tomb','imli-tamarind','incense','incense-burner','india-gate','india-gate-02','india-map','indian-flag','indian-flag-02','indian-food','indian-woman','indra','jagannatha','jaisalmer-fort','jalebi','jama-masjid','jantar-mantar','japa-mala','kalash-swastika','kali','kalki','kamadeva','kamdhenu','kandeel','kanji-vada','kapas-cotton','karma','karni-mata','kartikeya','kathakali','kheer','khuder-bhat','khunda','kite','konark-sun-temple','krishna','krishna-02','krishna-with-cow','kuber','kubera','kubera-02','kulfi','kumbh-kalash','kumkuma','kurma','laddu','ladoo','ladoo-bowl','lake-pichola','lakshmi','lal-qila','lantern','lantern-02','lassi','laung-clove','lingam','lion','lion-02','lotus','lotus-flower','lotus-temple','loudspeakers','mahabali','mala','malai-kofta','malai-kulfi','male-sikh','male-sikh02','mandala','mandala-02','mandap','mangala-snanam','mangalsutra','mango','mango-tree','mangoes','marigold','masala','masala-dosa','mathri','matka-water-jar','matsya','meditation','meditation-02','medu-vada','meenakshi-temple','mehndi-hand','mitra','mohini','momo','monkey','monkey-02','monkey-03','mortar-pestle','mridangam','mughlai-curry','murukku','naans','naga','naga-02','nallapusalu','namaste','namaste-hands','narasimha','nariyal-pani','nataraja','national-bravery','om','paan','palm-leaf-manuscript','paneer-makhani','pangong-tso','pankha-hand-fan','parashurama','parashurama-02','parvati','pav-bhaji','peacock','peda','pichkari','pinda-sweda','pongal','pongal-02','prambanan','prayer-wheel','priest','puja','pundit','qutub-minar','radha','rajpath','raksha-bandhan','raksha-bandhan-02','rama','rangoli','rashtrapati-bhavan','ravana','rice-sack','rocket-firecracker','rudraksha','rupee-coin','rupee-note','saag-paneer','sacred-cow','sadhya','samosa','samosa-chai','samosas','sandesh','sansad-bhavan','sanskrit','santoor','sapta-matrika','saptapadi','saraswati','sari','sarod','scroll','scroll-02','scroll-03','scroll-quill','scroll-rolled','scroll-rolled02','sesha','shakha-pola','shakti','shani','shankh','shehnai','shirodhara','shiva','shola-ghar','shree','sindoor','sita','sitar','sitar-02','snake','stupa','surya','surya-dev','svadhishthana','swan','swarmandal','swastika','swastika-02','swastika-book','swastika-lotus','tabla','tabla-02','tabla-03','taj-mahal','tanpura','temple','thali','thandai','third-eye','tiger','tiger-02','tikka-masala','tilak','tiranga-halwa','toran','toran-02','toran-lights','tridevi','trishul','trishul-02','tulsi','turban-02','turla-turban-crest','vada-pav','vajra','vamana','varaha','varaha-02','varuna','vasudeva','vedas','veena','vishnu','vishnu-02','vishwakarma','war-memorial','wedding-invitation','wedding-mandap','wheat','yagna','yagna-02','yama','yantra'] as const;

/** Type representing a valid icon name. */
export type iIconName = (typeof icons)[number];

/** Hindi alias -> canonical icon name. Both render the same glyph. */
export const aliases: Record<string, iIconName> = {
  'adrak': 'adrak-ginger',
  'agni': 'agni-dev',
  'agra-ka-kila': 'agra-fort',
  'lal-kila-agra': 'agra-fort',
  'ahimsa': 'ahimsa-hand',
  'anahat': 'anahata-chakra',
  'payal': 'anklet',
  'payal-02': 'anklet-02',
  'agni-baan': 'arrow-fire',
  'ashirvad': 'ashirwad-blessing',
  'blessing': 'ashirwad-blessing',
  'auto': 'auto-rickshaw',
  'rickshaw': 'auto-rickshaw',
  'auto-02': 'auto-rickshaw-02',
  'ayurved': 'ayurveda',
  'ayurved-katori': 'ayurvedic-bowl',
  'okhli': 'ayurvedic-mortar',
  'bali-mandir': 'balinese-pura',
  'pura': 'balinese-pura',
  'bargad': 'banyan-tree',
  'bhang': 'bhang-leaf',
  'bhangra': 'bhangra-dancer',
  'bhikshu': 'bhikkhu-monk',
  'sadhu': 'bhikkhu-monk',
  'bindi-wali': 'bindi-woman',
  'bodhi': 'bodhi-leaf',
  'peepal-patta': 'bodhi-leaf',
  'brahmin': 'brahman-elder',
  'pandit-ji': 'brahman-elder',
  'bail': 'bull',
  'nandi': 'bull',
  'bail-02': 'bull-02',
  'bandanwar-mala': 'bunting-garland',
  'ganatantra-divas': 'calendar-republic-day',
  'chakra': 'chakras',
  'chandan-lep': 'chandan',
  'chandra-devta': 'chandra',
  'chand': 'chandra-02',
  'char-minar': 'charminar',
  'chhatra': 'chhatra-parasol',
  'chhatri': 'chhatra-parasol',
  'chikki': 'chiki',
  'lal-mirch': 'chilli-pepper',
  'mirchi': 'chilli-pepper',
  'chutney': 'chutney-jar',
  'saap': 'cobra',
  'nariyal-doodh': 'coconut-milk',
  'nariyal-tel': 'coconut-oil',
  'nariyal-ka-ped': 'coconut-palm',
  'nariyal-ke-ped': 'coconut-palms',
  'sikka-purana': 'coin',
  'rang-balti': 'colour-bucket',
  'gaay': 'cow',
  'gaay-02': 'cow-02',
  'gaay-03': 'cow-03',
  'gend': 'cricket-ball',
  'balla': 'cricket-bat',
  'cricket-topi': 'cricket-cap',
  'dastane': 'cricket-gloves',
  'pads': 'cricket-pads',
  'maidan': 'cricket-stadium',
  'stumps': 'cricket-stumps',
  'viket': 'cricket-stumps',
  'trophy': 'cricket-trophy',
  'ampayar': 'cricket-umpire',
  'khiladi': 'cricketer',
  'sabzi-katori': 'curry-bowl',
  'chawal-sabzi': 'curry-rice',
  'dalchini': 'dalchini-cinnamon',
  'damru': 'damaru',
  'jhumka': 'dangle-earrings',
  'jhumka-02': 'dangle-earrings-02',
  'hiran': 'deer',
  'hiran-02': 'deer-02',
  'a': 'devanagari-a',
  'aa': 'devanagari-aa',
  'ae': 'devanagari-ae',
  'ai': 'devanagari-ai',
  'au': 'devanagari-au',
  'aw': 'devanagari-aw',
  'ba': 'devanagari-ba',
  'bha': 'devanagari-bha',
  'cha': 'devanagari-cha',
  'chha': 'devanagari-chha',
  'da': 'devanagari-da',
  'dda': 'devanagari-dda',
  'dda-nukta': 'devanagari-dda-nukta',
  'ddha': 'devanagari-ddha',
  'ddha-nukta': 'devanagari-ddha-nukta',
  'dha': 'devanagari-dha',
  'e': 'devanagari-e',
  'fa': 'devanagari-fa',
  'ga': 'devanagari-ga',
  'gha': 'devanagari-gha',
  'ghha': 'devanagari-ghha',
  'ha': 'devanagari-ha',
  'i': 'devanagari-i',
  'ii': 'devanagari-ii',
  'ja': 'devanagari-ja',
  'jha': 'devanagari-jha',
  'ka': 'devanagari-ka',
  'kha': 'devanagari-kha',
  'khha': 'devanagari-khha',
  'la': 'devanagari-la',
  'li': 'devanagari-li',
  'lla': 'devanagari-lla',
  'llha': 'devanagari-llha',
  'lri': 'devanagari-lri',
  'ma': 'devanagari-ma',
  'na': 'devanagari-na',
  'nga': 'devanagari-nga',
  'nna': 'devanagari-nna',
  'nya': 'devanagari-nya',
  'o': 'devanagari-o',
  'pa': 'devanagari-pa',
  'pha': 'devanagari-pha',
  'qa': 'devanagari-qa',
  'ra': 'devanagari-ra',
  'ri': 'devanagari-ri',
  'rra': 'devanagari-rra',
  'rri': 'devanagari-rri',
  'sa': 'devanagari-sa',
  'sha': 'devanagari-sha',
  'ssa': 'devanagari-ssa',
  'ta': 'devanagari-ta',
  'tha': 'devanagari-tha',
  'tta': 'devanagari-tta',
  'ttha': 'devanagari-ttha',
  'u': 'devanagari-u',
  'uu': 'devanagari-uu',
  'va': 'devanagari-va',
  'ya': 'devanagari-ya',
  'yya': 'devanagari-yya',
  'za': 'devanagari-za',
  'devi-netra': 'devi-eyes',
  'dhanteras': 'dhanteras-kalash',
  'dhanush-purana': 'dhanush',
  'bow-arrow': 'dhanush-baan',
  'dhol-02': 'dhol-drum',
  'diwali-diye': 'diwali-candles',
  'diwali-deepak': 'diwali-lamps',
  'phuljhadi': 'diwali-sparkles',
  'deepak': 'diya',
  'deepak-02': 'diya-02',
  'deepak-03': 'diya-03',
  'deepak-04': 'diya-04',
  'palki': 'doli',
  'haathi': 'elephant',
  'haathi-02': 'elephant-02',
  'ananta-granthi': 'endless-knot',
  'sardar-chehra': 'face-male-sikh',
  'parivar': 'family-gathering',
  'stri': 'female',
  'jhandi': 'festive-flags',
  'pataka-purana': 'firecracker',
  'pataka-02': 'firecracker-02',
  'pataka': 'firecraker',
  'bansuri': 'flute',
  'charan': 'footprint',
  'paduka': 'footprint',
  'gadaa': 'gada',
  'ganga': 'ganges-river',
  'ganga-nadi': 'ganges-river',
  'gateway': 'gateway-of-india',
  'ghee': 'ghee-jar',
  'giddha': 'giddha-dancer',
  'harmandir-sahib': 'golden-temple',
  'swarn-mandir': 'golden-temple',
  'gujiya': 'gujia',
  'gurudwara': 'gurdwara',
  'guruji': 'guru',
  'haar': 'haar-necklace',
  'maala': 'haar-necklace',
  'turmeric': 'haldi',
  'evil-eye': 'hamsa-eye',
  'nazar': 'hamsa-eye',
  'hamsa': 'hamsa-hand',
  'haath-mein-rupaya': 'hand-holding-rupee',
  'haath-rupaya': 'hand-rupee-02',
  'handi': 'handi-pot',
  'baja': 'harmonium',
  'peti': 'harmonium',
  'havan-agni': 'havan-fire',
  'hawa-mahal-jaipur': 'hawa-mahal',
  'mehndi': 'henna-hand',
  'jadi-booti': 'herbal-leaf',
  'bhagwa-dhwaj': 'hinduist-flag',
  'havan': 'homa-havan',
  'yagya': 'homa-havan',
  'hukka': 'hookah',
  'humayun-ka-maqbara': 'humayuns-tomb',
  'imli': 'imli-tamarind',
  'agarbatti-purani': 'incense',
  'agarbatti': 'incense-burner',
  'dhoop-daani': 'incense-burner',
  'india-gate-dilli': 'india-gate',
  'bharat-naksha': 'india-map',
  'tiranga': 'indian-flag',
  'tiranga-02': 'indian-flag-02',
  'bhojan': 'indian-food',
  'bharatiya-nari': 'indian-woman',
  'jaisalmer': 'jaisalmer-fort',
  'sonar-kila': 'jaisalmer-fort',
  'jap-mala': 'japa-mala',
  'kamdhenu-gau': 'kamdhenu',
  'akash-kandil': 'kandeel',
  'kandil': 'kandeel',
  'kapas': 'kapas-cotton',
  'rui': 'kapas-cotton',
  'karm': 'karma',
  'kathakali-nritya': 'kathakali',
  'khanda': 'khunda',
  'sword': 'khunda',
  'patang': 'kite',
  'konark': 'konark-sun-temple',
  'kalash': 'kumbh-kalash',
  'purna-kumbha': 'kumbh-kalash',
  'kumkum': 'kumkuma',
  'sindoor-daani': 'kumkuma',
  'laddoo': 'ladoo',
  'ladoo-katori': 'ladoo-bowl',
  'pichola-jheel': 'lake-pichola',
  'red-fort': 'lal-qila',
  'laalten': 'lantern',
  'laalten-02': 'lantern-02',
  'laung': 'laung-clove',
  'shivling': 'lingam',
  'sher': 'lion',
  'sher-02': 'lion-02',
  'kamal-phool': 'lotus',
  'kamal': 'lotus-flower',
  'kamal-mandir': 'lotus-temple',
  'bhonpu': 'loudspeakers',
  'speaker': 'loudspeakers',
  'maala-purani': 'mala',
  'sardar': 'male-sikh',
  'sardar-02': 'male-sikh02',
  'mandal': 'mandala',
  'mandal-02': 'mandala-02',
  'mangal-snan': 'mangala-snanam',
  'mangal-sutra': 'mangalsutra',
  'aam': 'mango',
  'aam-ka-ped': 'mango-tree',
  'aam-fal': 'mangoes',
  'genda': 'marigold',
  'genda-phool': 'marigold',
  'ghada': 'matka-water-jar',
  'matka': 'matka-water-jar',
  'dhyaan': 'meditation',
  'dhyaan-02': 'meditation-02',
  'meenakshi': 'meenakshi-temple',
  'mehndi-haath': 'mehndi-hand',
  'bandar': 'monkey',
  'bandar-02': 'monkey-02',
  'bandar-03': 'monkey-03',
  'imam-dasta': 'mortar-pestle',
  'okhli-musal': 'mortar-pestle',
  'mridang': 'mridangam',
  'mughlai': 'mughlai-curry',
  'chakli': 'murukku',
  'naan-roti': 'naans',
  'naag': 'naga',
  'naag-02': 'naga-02',
  'nalla-pusalu': 'nallapusalu',
  'namaskar-purana': 'namaste',
  'namaskar': 'namaste-hands',
  'pranam': 'namaste-hands',
  'veerta-puraskar': 'national-bravery',
  'omkar': 'om',
  'tadpatra': 'palm-leaf-manuscript',
  'pangong-jheel': 'pangong-tso',
  'haath-pankha': 'pankha-hand-fan',
  'pankha': 'pankha-hand-fan',
  'mor': 'peacock',
  'pichkaari': 'pichkari',
  'pind-swed': 'pinda-sweda',
  'pongal-parv': 'pongal',
  'pongal-02-parv': 'pongal-02',
  'mani-chakra': 'prayer-wheel',
  'pujari': 'priest',
  'pooja': 'puja',
  'pandit': 'pundit',
  'qutub': 'qutub-minar',
  'kartavya-path': 'rajpath',
  'rakhi': 'raksha-bandhan',
  'rakhi-02': 'raksha-bandhan-02',
  'rangoli-kolam': 'rangoli',
  'rashtrapati-bhawan': 'rashtrapati-bhavan',
  'chawal-bora': 'rice-sack',
  'rocket-pataka': 'rocket-firecracker',
  'rudraaksh': 'rudraksha',
  'rupaya': 'rupee-coin',
  'sikka': 'rupee-coin',
  'note': 'rupee-note',
  'rupaya-note': 'rupee-note',
  'gau-mata': 'sacred-cow',
  'samosa-purana': 'samosa',
  'samose': 'samosas',
  'parliament': 'sansad-bhavan',
  'sansad-bhawan': 'sansad-bhavan',
  'santur': 'santoor',
  'saat-phere': 'saptapadi',
  'saree': 'sari',
  'patra': 'scroll',
  'conch': 'shankh',
  'shahnai': 'shehnai',
  'shirodhaara': 'shirodhara',
  'shri': 'shree',
  'sindur': 'sindoor',
  'saanp': 'snake',
  'stoop': 'stupa',
  'surya-devta': 'surya-dev',
  'swadhisthan': 'svadhishthana',
  'hans': 'swan',
  'swastik': 'swastika',
  'swastik-02': 'swastika-02',
  'swastik-granth': 'swastika-book',
  'swastik-kamal': 'swastika-lotus',
  'taj': 'taj-mahal',
  'mandir': 'temple',
  'thaali': 'thali',
  'teesri-aankh': 'third-eye',
  'baagh': 'tiger',
  'baagh-02': 'tiger-02',
  'teeka': 'tilak',
  'bandanwar': 'toran-lights',
  'trishool': 'trishul',
  'trident-02': 'trishul-02',
  'trishool-02': 'trishul-02',
  'tulsi-patta': 'tulsi',
  'pagdi-02': 'turban-02',
  'kalgi': 'turla-turban-crest',
  'turra': 'turla-turban-crest',
  'thunderbolt': 'vajra',
  'vajr': 'vajra',
  'ved': 'vedas',
  'been': 'veena',
  'yudh-smarak': 'war-memorial',
  'nimantran': 'wedding-invitation',
  'shaadi-card': 'wedding-invitation',
  'shaadi-mandap': 'wedding-mandap',
  'vivah-mandap': 'wedding-mandap',
  'gehun': 'wheat',
  'yagya-purana': 'yagna',
  'yagya-02': 'yagna-02',
  'yantr': 'yantra',
};

/** Every alias name. */
export const aliasNames = Object.keys(aliases) as readonly string[];

/** Resolve an icon name or Hindi alias to the canonical icon name. */
export function resolveIcon(name: string): iIconName | undefined {
  if ((icons as readonly string[]).includes(name)) return name as iIconName;
  return aliases[name];
}

/** Category names, in display order. */
export const categoryNames = ['Deities','Sacred Symbols','Devanagari Script','Temples & Architecture','Landscapes','Festivals & Rituals','Food & Drink','Music & Dance','People & Attire','Ritual & Everyday Objects','Nature & Animals','Cricket'] as const;

/** Type representing a valid category. */
export type iIconCategory = (typeof categoryNames)[number];

/** Icon names grouped by category — use this to render a categorised icon list. */
export const categories: Record<iIconCategory, readonly iIconName[]> = {
  'Deities': ['aditi','agni-dev','alamelu','ardhanareeswara','ardhanarishvara-02','ashoka','ayyappa','balaji','balarama','brahma','brihaspati','buddha','chandi','chandra','devi','devi-eyes','durga','ganesha','ganga-devi','garuda','gayatri','guru','hanumaan','hanumaan-02','hanuman-02','harihara','indra','jagannatha','kali','kalki','kamadeva','kamdhenu','karni-mata','kartikeya','krishna','krishna-02','krishna-with-cow','kuber','kubera','kubera-02','kurma','lakshmi','mahabali','matsya','mitra','mohini','narasimha','nataraja','parashurama','parashurama-02','parvati','radha','rama','ravana','sapta-matrika','saraswati','sesha','shakti','shani','shiva','sita','surya','surya-dev','tridevi','vamana','varaha','varaha-02','varuna','vasudeva','vishnu','vishnu-02','vishwakarma','yama'],
  'Sacred Symbols': ['ahimsa-hand','anahata-chakra','arrow-fire','ashirwad-blessing','ashoka-chakra','bodhi-leaf','chakra-02','chakras','chandan','chandra-02','chhatra-parasol','dhanush','dhanush-baan','endless-knot','footprint','gada','granth-om','granth-swastika','hamsa-eye','hamsa-hand','hinduist-flag','kalash-swastika','karma','khunda','lingam','mala','mandala','mandala-02','meditation','meditation-02','naga','naga-02','namaste','namaste-hands','om','prayer-wheel','rangoli','rudraksha','shankh','shree','sindoor','svadhishthana','swastika','swastika-02','swastika-book','swastika-lotus','third-eye','tilak','trishul','trishul-02','vajra','vedas','yantra'],
  'Devanagari Script': ['devanagari-a','devanagari-aa','devanagari-ae','devanagari-ai','devanagari-au','devanagari-aw','devanagari-ba','devanagari-bha','devanagari-cha','devanagari-chha','devanagari-da','devanagari-dda','devanagari-dda-nukta','devanagari-ddha','devanagari-ddha-nukta','devanagari-dha','devanagari-e','devanagari-fa','devanagari-ga','devanagari-gha','devanagari-ghha','devanagari-ha','devanagari-i','devanagari-ii','devanagari-ja','devanagari-jha','devanagari-ka','devanagari-kha','devanagari-khha','devanagari-la','devanagari-li','devanagari-lla','devanagari-llha','devanagari-lri','devanagari-ma','devanagari-na','devanagari-nga','devanagari-nna','devanagari-nya','devanagari-o','devanagari-pa','devanagari-pha','devanagari-qa','devanagari-ra','devanagari-ri','devanagari-rra','devanagari-rri','devanagari-sa','devanagari-sha','devanagari-ssa','devanagari-ta','devanagari-tha','devanagari-tta','devanagari-ttha','devanagari-u','devanagari-uu','devanagari-va','devanagari-ya','devanagari-yya','devanagari-za','hindi-akshar','sanskrit'],
  'Temples & Architecture': ['agra-fort','balinese-pura','charminar','gateway-of-india','golden-temple','gurdwara','hawa-mahal','humayuns-tomb','india-gate','india-gate-02','india-map','jaisalmer-fort','jama-masjid','jantar-mantar','konark-sun-temple','lal-qila','lotus-temple','meenakshi-temple','national-bravery','prambanan','qutub-minar','rajpath','rashtrapati-bhavan','sansad-bhavan','shola-ghar','stupa','taj-mahal','temple','war-memorial'],
  'Landscapes': ['ganges-river','lake-pichola','pangong-tso'],
  'Festivals & Rituals': ['aarti','aarti-02','ayurveda','bodhu-boron','bunting-garland','calendar-holi','calendar-kite','calendar-om','calendar-pongol','calendar-republic-day','calendar-swastika','chhikka','colour-bucket','dhanteras-kalash','diwali-candles','diwali-lamps','diwali-sparkles','diya','diya-02','diya-03','doli','family-gathering','festive-flags','firecracker','firecracker-02','firecraker','havan-fire','holi','homa-havan','incense','kite','kumbh-kalash','loudspeakers','mandap','mangala-snanam','nallapusalu','pichkari','pongal','pongal-02','puja','raksha-bandhan','raksha-bandhan-02','rocket-firecracker','saptapadi','shakha-pola','shirodhara','toran','toran-02','toran-lights','wedding-invitation','wedding-mandap','yagna','yagna-02'],
  'Food & Drink': ['adrak-ginger','baati','barfi','bhang-leaf','biryani','chai','chiki','chilli-pepper','chutney-jar','coconut-milk','coconut-oil','curry-bowl','curry-rice','dalchini-cinnamon','dum-aloo','falooda','ghee-jar','gujia','gulab-jamun','haldi','handi-pot','herbal-leaf','imli-tamarind','indian-food','jalebi','kanji-vada','kheer','khuder-bhat','kulfi','laddu','ladoo','ladoo-bowl','lassi','laung-clove','malai-kofta','malai-kulfi','mango','mangoes','masala','masala-dosa','mathri','matka-water-jar','medu-vada','momo','mughlai-curry','murukku','naans','nariyal-pani','paan','paneer-makhani','pav-bhaji','peda','rice-sack','saag-paneer','sadhya','samosa','samosa-chai','samosas','sandesh','thali','thandai','tikka-masala','tiranga-halwa','tulsi','vada-pav','wheat'],
  'Music & Dance': ['bhangra-dancer','damaru','dhol','dhol-drum','dholak','ektara','flute','giddha-dancer','harmonium','kathakali','mridangam','santoor','sarod','shehnai','sitar','sitar-02','swarmandal','tabla','tabla-02','tabla-03','tanpura','veena'],
  'People & Attire': ['anklet','anklet-02','bangles','bhikkhu-monk','bindi-woman','brahman-elder','dangle-earrings','dangle-earrings-02','face-male-sikh','female','haar-necklace','henna-hand','indian-woman','kumkuma','male-sikh','male-sikh02','mangalsutra','marigold','mehndi-hand','priest','pundit','sari','turban-02','turla-turban-crest'],
  'Ritual & Everyday Objects': ['auto-rickshaw','auto-rickshaw-02','ayurvedic-bowl','ayurvedic-mortar','coin','diya-04','hand-holding-rupee','hand-rupee-02','hookah','incense-burner','indian-flag','indian-flag-02','japa-mala','kandeel','kapas-cotton','lantern','lantern-02','mortar-pestle','palm-leaf-manuscript','pankha-hand-fan','pinda-sweda','rupee-coin','rupee-note','scroll','scroll-02','scroll-03','scroll-quill','scroll-rolled','scroll-rolled02'],
  'Nature & Animals': ['banyan-tree','bull','bull-02','cobra','coconut-palm','coconut-palms','cow','cow-02','cow-03','deer','deer-02','elephant','elephant-02','lion','lion-02','lotus','lotus-flower','mango-tree','monkey','monkey-02','monkey-03','peacock','sacred-cow','snake','swan','tiger','tiger-02'],
  'Cricket': ['cricket-ball','cricket-bat','cricket-cap','cricket-gloves','cricket-helmet','cricket-kit','cricket-pads','cricket-stadium','cricket-stumps','cricket-trophy','cricket-umpire','cricketer'],
};

/** Category for an icon name or alias. */
export function getCategory(name: string): iIconCategory | undefined {
  const key = resolveIcon(name);
  if (!key) return undefined;
  return (categoryNames as readonly string[]).find(
    (c) => categories[c as iIconCategory].includes(key)
  ) as iIconCategory | undefined;
}
